#%RAML 1.0 NamedExample
value:
-
    id: 1
    code: ENGCSDS0001
    name: Data Science
    field: ENG
    level: MS
    mode: FO
    duration: 12
    fees: 45000
    begins: 01-MAY-2018
-    
    id: 2
    code: ENGCSDS0002
    name: Data Science
    field: ENG
    level: DS
    mode: FO
    duration: 12
    fees: 45000
    begins: 01-MAY-2018